### ISSUE TITLE
Add plotting routines for submodels

### ISSUE THREAD

**Issue by sivogel** [hydpy-dev/hydpy#115]
This was mentioned in a comment on issue #90, but was not followed up on. Currently there are no plotting routines available for submodel time series (such as the main model's plot_flux_series()). It would be consistent and convenient to add this functionality also for submodels as well.

**Comment by tyralla** [comment]
Implemented by 373c52882fd9a54189a7062b22bcf460c5b0c608.

I also took the chance to support sequence types and instances for selecting what to plot. This now works with the unpacking operator (*), which is a breaking change but should not cause much trouble.
