### ISSUE TITLE
Saving wland model leads to Attribute Error since the introduction of the discharge submodel

### ISSUE THREAD

**Issue by sivogel** [hydpy-dev/hydpy#125]
While trying to set up a walrus model with a walrus_q and an evap submodel, I run into an error when saving the walrus controls:
![image](https://github.com/hydpy-dev/hydpy/assets/26409057/24bb42a5-6389-49bc-a7a0-e45ba81bde95)
"prepare_channeldepth" is called by all submodels of walrus, but only in the walrus-q- submodel  this method is implemented.

**Comment by tyralla** [comment]
Commits 137c148835f02db644e54dbe1b85483929d544d9 and dbd52db717a78c89db0b9ac667da88150db6ae62 should fix these problems.  Could you please verify?

**Comment by sivogel** [comment]
Thank you. The commits fixed my problems!
