### ISSUE TITLE
mistake in documentation of dam_model.Calc_ForcedDischarge_V1

### ISSUE THREAD

**Issue by parvumflumen** [hydpy-dev/hydpy#127]
There is a minor mistake in the documentation of hydpy.models.dam.dam_model.Calc_ForcedDischarge_V1[[source]](https://hydpy-dev.github.io/hydpy/master/_modules/hydpy/models/dam/dam_model.html#Calc_ForcedDischarge_V1): It should be r1=fsmoothlogistic1(WaterLevel−WaterLevelMaximumThreshold,WaterLevelMaximumSmoothPar) instead of r1=fsmoothlogistic1(WaterLevelMaximumThreshold−WaterLevel,WaterLevelMaximumSmoothPar). The code itself is correct.

**Comment by tyralla** [comment]
Thanks! Feel free to fix this via a pull request.
