### ISSUE TITLE
Incorrect Attribute Assignment in Rule Class in calibtools.py

### ISSUE THREAD

**Issue by parvumflumen** [hydpy-dev/hydpy#158]
In the file calibtools.py, within the __init__ method of the Rule class, an incorrect assignment is made to the parameterstep attribute. Currently, self.parameterstep = parameterstep is used, which leads to unexpected behavior due to the presence of a property parameterstep which returns the internal variable _parameterstep.
To fix this issue, line 690 should be modified to use the internal variable _parameterstep.

**Comment by tyralla** [comment]
Thanks for the report.  Could you please provide a small example of what is currently going wrong?

**Comment by parvumflumen** [comment]
I couldn't set the parameterstep but after revisiting the code I understand that this was due to the fact that the parameter was non-time-dependent, so it was set automatically to `None` by the setter function.
