### ISSUE TITLE
Add links in documentation of sequence features

### ISSUE THREAD

**Issue by sivogel** [hydpy-dev/hydpy#36]
Links to the functions using and generating this sequence in the sequence class would be helpful

**Comment by tyralla** [comment]
The documentation of each sequence class now links to all "hydrological" method classes (derived from `modeltools.Method`) that require, update, or calculate its value(s).  Additionally, the documentation of each parameter class links to all methods that require its value(s). 

One example:

![grafik](https://user-images.githubusercontent.com/25983587/68549714-8a49fa00-03fb-11ea-943b-9548206e7f0b.png)

Nice idea, it makes clicking through the documentation of a model much more comfortable. I will merge this feature into the master branch soon.
