### ISSUE TITLE
Model names in HydPy 6.0

### ISSUE THREAD

**Issue by tyralla** [hydpy-dev/hydpy#99]
In HydPy 5, model names are not overly consistent.  We aim to improve this in HydPy 6.0.  The following table lists the current and future names.  The future names are still open for discussion.  Hence, I will edit the table until we agree on all names.   The discussion can take place as additional comments, as usual.

| HydPy 5.0 <br/> source code | HydPy 6.0 <br/> source code| HydPy 6.0 <br/> documentation  |
| -------------- | -------------------| ------------------------------------------------------------------------ |
| arma_v1        | arma_rimorido    | HydPy-ARMA-RIMO/RIDO (nonlinear routing by multiple ARMA processes) |
| conv_v001    | conv_nn               | HydPy-Conv-NN (nearest neighbour interpolation) |
| conv_v002    | conv_idw             | HydPy-Conv-IDW (inverse distance weighted interpolation) |
| conv_v003    | conv_idw_ed        | HydPy-Conv-IDW-ED (inverse distance weighted interpolation with external drift) |
| dam_v001     | ?                           | ? |
| dam_v002     | ?                           | ? |
| dam_v003     | ?                           | ? |
| dam_v004     | ?                           | ? |
| dam_v005     | ?                           | ? |
| dam_v006     | dam_llake             | HydPy-Dam-L-Lake (controlled lake model adopted from LARSIM) |
| dam_v007     | dam_lretention     | HydPy-Dam-L-RB (retention basin model adopted from LARSIM) |
| dam_v008     | dam_lreservoir      | HydPy-Dam-L-Res (reservoir model adopted from LARSIM) |
|                      | dam_pump      | HydPy-Dam-Pump (pumping station model) |
|                      | dam_sluice      | HydPy-Dam-Sluice (sluice model) |
|                      | dam_pump_sluice      | HydPy-Dam-Pump-Sluice (pumping station with sluice model) |
| dummy_v1    | dummy_node2node | HydPy-Dummy-Node2Node (dummy model passing data from inlet to outlet nodes) |
|                      | dummy_interceptedwater | HydPy-Dummy-InterceptedWater (dummy model supplying main models with intercepted water states) |
|                      | dummy_soilwater | HydPy-Dummy-SoilWater (dummy model supplying main models with soil water states) |
|                      | dummy_snowcover | HydPy-Dummy-SnowCover (dummy model supplying main models with snow cover states) |
|                      | dummy_snowycanopy | HydPy-Dummy-SnowyCanopy (dummy model supplying main models with snow cover degrees in canopies) |
|                      | dummy_snowalbedo | HydPy-Dummy-SnowAlbedo (dummy model supplying main models with snow albedo states) |
| evap_v001    | evap_ret_fao56    | HydPy-Evap-RET-FAO56 (FAO-56 Penman-Monteith reference evapotranspiration) |
|                      | evap_ret_tw2002 | HydPy-Evap-RET-TW2002 (Turc-Wendling reference evapotranspiration, 2002) |
|                      | evap_ret_io          | HydPy-Evap-RET-IO (external data) |
|                      | evap_pet_m         | HydPy-Evap-PET-M (month-based adjustment of reference evapotranspiration) |
|                      | evap_pet_mlc       | HydPy-Evap-PET-M-LC (month-based land cover adjustment of reference evapotranspiration) |
|                      | evap_pet_ambav1  | HydPy-Evap-PET-AMBAV-1.0 (potential evapotranspiration based on AMBAV 1.0) |
|                      | evap_pet_hbv96   | HydPy-Evap-PET-HBV96 (potential evapotranspiration after HBV96) |
|                      | evap_aet_hbv96   | HydPy-Evap-AET-HBV96 (actual evapotranspiration after HBV96) |
|                      | evap_aet_minhas  | HydPy-Evap-AET-Minhas (actual evapotranspiration based on the Minhas equation) |
|                      | evap_aet_morsim | HydPy-Evap-AET-MORSIM (actual evapotranspiration based on MORECS/LARSIM) |
| exch_v001     | exch_weir_hbv96  | HydPy-Exch-Weir-HBV96 (weir model adopted from IHMS-HBV96) |
|                      | exch_waterlevel   | HydPy-Exch-WL (submodel for querying the water level from a remote node) |
|                      | gland_gr4  | HydPy-G-GR4 (Génie Rural model with 4 parameters) |
|                      | gland_gr5   | HydPy-G-GR5 (Génie Rural model with 5 parameters)  |
|                      | gland_gr6   | HydPy-G-GR6 (Génie Rural model with 6 parameters) |
| hbranch_v1   | exch_branch_hbv96 | HydPy-Exch-Branch-HBV96 (branch model adopted from IHMS-HBV96) |
|                      | ga_garto               | HydPy-GA-GARTO (main model for calculating the Green-Ampt / Talbot-Ogden infiltration with redistribution)
|                      | ga_garto_submodel1 | HydPy-GA-GARTO-Sub1 (submodel for calculating the Green-Ampt / Talbot-Ogden infiltration with redistribution)
| hland_v1       | hland_96               | HydPy-H-HBV96 (adoption of SMHI-IHMS-HBV96) |
| hland_v2       |                              | (obsolete after extracting the unit hydrograph / linear storage cascade) |
| hland_v3       | hland_96p            | HydPy-H-HBV96-PREVAH (fusion of SMHI-IHMS-HBV96 and PREVAH) |
| hland_v4       | hland_96c             | HydPy-H-HBV96-COSERO (fusion of SMHI-IHMS-HBV96 and COSERO) |
| lland_v1        | lland_dd               | HydPy-L-DD (adoption of LARSIM with degree day-based snow modelling) |
| lland_v2        |                               | (obsolete after extracting Turc-Wendling / reading reference evapotranspiration) |
| lland_v3        | lland_knauf            | HydPy-L-Knauf (adoption of LARSIM with Knauf-based snow modelling) |
| lland_v4        | lland_knauf_ic    | HydPy-L-Knauf-Ic (adoption of LARSIM with Knauf-based snow modelling including snow interception) |
| lstream_v001 | kinw_williams        | HydPy-KinW-Williams (Williams routing based on a triple trapeze profile and the Strickler equation) |
| lstream_v002 | kinw_williams_ext | HydPy-KinW-Williams-Ext (Williams routing based on an externally calculated volume-discharge relationship ) |
| llake_v1         |                              | (can be removed, replaced by dam_v006 for a long time now) |
| meteo_v001  | meteo_glob_fao56 | HydPy-Meteo-Glob-FAO56 (global radiation estimation adopted from FAO56) |
| meteo_v002  | meteo_sun_fao56     | HydPy-Meteo-Sun-FAO56 (sunshine duration estimation adopted from FAO56) |
| meteo_v003  | meteo_glob_morsim | HydPy-Meteo-Glob-MORSIM (global radiation estimation adopted from MORECS/LARSIM) |
| meteo_v004  | meteo_sun_morsim | HydPy-Meteo-Sun-MORSIM (sunshine duration estimation adopted from MORECS/LARSIM) |
|                      | meteo_glob_io     | HydPy-Meteo-Glob-IO (external global radiation data) |
|                      | meteo_clear_glob_io | HydPy-Meteo-Clear-Glob-IO (external clear sky and global radiation data) |
|                      | meteo_psun_sun_glob_io | HydPy-PSun-Sun-Glob-IO (external possible and actual sunshine duration and global radiation data) |
|                      | meteo_precip_io   | HydPy-Meteo-Precip-IO (external precipitation data) |
|                      | meteo_temp_io   | HydPy-Meteo_Temp-IO (external temperature data) |
| musk_classic | musk_classic          | HydPy-Musk-Classic (classic Muskingum routing, compatible with SMHI-IHMS-HBV96) |
| musk_mct    | musk_mct               | HydPy-Musk-MCT (Muskingum-Cunge-Todini routing) |
|                      | rconc_uh               | HydPy-Rconc-UH (Unit Hydrograph runoff concentration, compatible with HBV96 and GR4J) |
|                      | rconc_nash            | HydPy-Rconc-Nash (Nash-Cascade runoff concentration) |
|                      | snow_cn               | HydPy-Snow-CemaNeige (Cema-Neige model with mean temperature as input)|
|                      | snow_cn_temprange   | HydPy-Snow-CemaNeige-TempRange (Cema-Neige model with minimum and maximum temperature as input) |
|                      | sw1d_channel      | HydPy-SW1D-Channel ("user model" for preparing single channels that will be combined and solved by  HydPy-SW1D-Network)|
|                      | sw1d_network     | HydPy-SW1D-Network ("composite model" for solving the 1-dimensional shallow water equations in channel networks) |
|                      | sw1d_lias              | HydPy-SW1D-LIAS (submodel for calculating the discharge between two channel segments based on Bates et al. (2010) and Almeida et al. (2012) |
|                      | sw1d_lias_sluice    | HydPy-SW1D-LIAS/Sluice (submodel that extends HydPy-SW1D-LIAS with sluice functionalities) |
|                      | sw1d_pump          | HydPy-SW1D-Pump (submodel for pumping water between two channel segments) |
|                      | sw1d_storage        | HydPy-SW1D-Storage (submodel for calculating a single channel segment's water balance) |
|                      | sw1d_q_in             | HydPy-SW1D-Q-In (submodel for adding pre-determined discharge to a channel inlet) |
|                      | sw1d_q_out           | HydPy-SW1D-Q-Out (submodel for subtracting pre-determined discharge from a channel outlet) |
|                      | sw1d_weir_out       | HydPy-SW1D-Weir-Out (submodel for calculating free weir flow at a channel outlet) |
|                      | sw1d_gate_out       | HydPy-SW1D-Gate-Out (submodel for calculating flow under a submerged gate at a channel outlet) |
| test_v1         | test_stiff0d              | HydPy-Test-Stiff-0D (test model for stiff ODEs and scalar sequences) |
| test_v2         | test_discontinous   | HydPy-Test-Discontinuous (test model for discontinuous ODEs) |
| test_v3         | test_stiff1d             | HydPy-Test-Stiff-1D (test model for stiff ODEs and 1-dimensional sequences) |
| wland_v001  | wland_wag             | HydPy-W-Wag (extended version of the original Wageningen WALRUS model) |
| wland_v002  | wland_gd               | HydPy-W-GD (extended version of the WALRUS model with modified groundwater dynamics) |
|                      | wq_walrus                | HydPy-WQ-WALRUS (WALRUS default function for calculating catchment outflow) |
|                      | wq_trapeze               | HydPy-WQ-Trapeze (multi-trapeze river profile submodel) |
|                      | wq_trapeze_strickler | HydPy-WQ-Trapeze-Strickler (multi-trapeze river profile submodel including Strickler-based calculations) |

**Comment by tyralla** [comment]
I would say we have three types of application model names:

- The short one.  We use it in Python code and the technical part of the online documentation (as a link).  It usually consists (or should consist) of the base model's name and a concise description, separated by an underscore.  Example: `musk_mct`.
- The long one.  We use it for introducing a new model, e.g. in the title of the model's documentation.  It consists of the literal "HydPy", the base model's name, and a short description, all separated by dashes.  Also, we append a more exhaustive explanation in brackets that should be even helpful when encountering the model for the first time.  Example: *HydPy-Musk-MCT (Muskingum-Cunge-Todini)*.
- The intermediate one, for when the short name appears too technical and the long one too long.  Example: *Musk-MCT*.

**Comment by tyralla** [comment]
If find naming the `hland...`, `lland...`, and `wland...` models particularly difficult.  For these models, modularisation allows reducing the number of different application models stemming from the same base model.   Ideally, the main models would be flexible enough and the set of submodels complete enough so that only one child model would be necessary in each case...

**Comment by tyralla** [comment]
I added [evap_io](https://hydpy-dev.github.io/hydpy/master/evap_io.html) to the table above.

**Comment by tyralla** [comment]
I still do not know if we will keep them as independent models or merge them into other Evap models but I added preliminary names for `evap_lc` and `evap_mlc`.

**Comment by tyralla** [comment]
Same for `evap_m`.

**Comment by tyralla** [comment]
I nearly finished `evap_hbv96` and suggest the full name "HydPy-Evap-HBV96 (potential evaporation after HBV96").  However, for `hland_v1`, I suggested `hland_96`.  A little inconsistent...

**Comment by tyralla** [comment]
The [main models can be sub-submodels](https://github.com/hydpy-dev/hydpy/issues/95#issuecomment-1447953657) idea seems to be a good one.  Hence, we really need something like a `precip_io` model.  However, introducing a new model family named `precip` does not seem right, especially if `precip_io` would stay the only application model ever.  So, adding it to the `meteo` family seems preferable.  My suggestion for the new application model's name thus is `meteo_precip_io`.  (`meteo_p_io` could be an alternative, but "p" could also stand for pressure).

**Comment by tyralla** [comment]
`meteo_precip_io` would be the first application model name with two underscores.

**Comment by tyralla** [comment]
A added `meteo_temp_io`.

**Comment by tyralla** [comment]
I changed `evap_hbv96` to `evap_pet_hbv96` for a reason discussed [here](https://github.com/hydpy-dev/hydpy/issues/109#issuecomment-1473408946).

**Comment by tyralla** [comment]
I removed `evap_lc`, which is currently not required.

**Comment by tyralla** [comment]
I added `evap_aet_hbv96`, which still requires some documentation updates but seems to work fine now.

**Comment by tyralla** [comment]
I changed the name `dummy_v1` to `dummy_n2n`.

**Comment by tyralla** [comment]
I added `dummy_ic`, `dummy_sw`, and `dummy_sc` to the table.  These models will now serve for testing `evap_aet_hbv96` independently from a main model like `hland_v1` and later for playing around with different approaches to calculate actual evapotranspiration and other properties to be calculated by submodels.  

Adding them to the `test` model family is also an option.  However, the `test` models are for model developers and provide actual mathematics, so I think the `dummy` model family fits slightly better.

**Comment by tyralla** [comment]
I added `evap_minhas` to the table (which should be in the master branch by today).   This model is factored out from `lland_v1` and applies an equation introduced by [Minhas et al. (1974)](https://agupubs.onlinelibrary.wiley.com/doi/abs/10.1029/WR010i003p00383) to calculate potential evapotranspiration to soil evapotranspiration. Initially, we took this approach from LARSIM-ME, but as there is nothing LARSIM-specific here, I would prefer to let the name refer to the original authors. Like for `evap_tw2002`.

**Comment by tyralla** [comment]
I added the `dummy` models `dummy_snowycanopy ` and `dummy_snowalbedo` and gave the others more descriptive names. The names are very long, but this should likely bother no one because these models will probably be only used for testing purposes and are of little relevance to model users.

**Comment by tyralla** [comment]
I added (preliminary versions) of [dam_pump](https://hydpy-dev.github.io/hydpy/master/dam_pump.html), [dam_sluice](https://hydpy-dev.github.io/hydpy/master/dam_sluice.html), and [dam_pump_sluice](https://hydpy-dev.github.io/hydpy/master/dam_pump_sluice.html) to the master branch and updated the above table.

**Comment by tyralla** [comment]
I added `sw1d_channel`, `sw1d_network`, `sw1d_storage`, `sw1d_lias`, `sw1d_q_in`, `sw1d_q_out`, and `sw1d_weir_out` to the table.

**Comment by tyralla** [comment]
I added `sw1d_lias_sluice` and `sw1d_gate_out ` to the table.  Suggestions for more precise words than `sluice` and `gate` are welcome!

**Comment by tyralla** [comment]
I added `exch_waterlevel` and `q_walrus`.

**Comment by tyralla** [comment]
I added `evap_pet_ambav1`.

**Comment by tyralla** [comment]
I added `meteo_glob_io`, `meteo_clear_glob_io`, and `meteo_psun_sun_glob_io `.

**Comment by BGWKlein** [comment]
For meteo and evap models I propose the naming convention:
evap|meteo_[parameter1]<_[parameter2]><_[parameter3]>_[method]

new model names according to this convention:

meteo_glob_fao56 instead of meteo_fao56glob
meteo_sd_fao56 instead of meteo_fao56sd
meteo_glob_larsim instead of meteo_lglob (probably another method name for larsim? thompsen?)
meteo_sd_larsim instead of meteo_lsd (probably another method name for larsim? thompsen?)

evap_rep_io instead of evap_io
and so on

**Comment by BGWKlein** [comment]
I propose model name
wland_wag(eningen) instead of wland_orig

**Comment by tyralla** [comment]
Yes, making the names of `evap` and `meteo` makes sense.  I will adjust the table.  

`wland_wag` and `wland_orig` are both only half-true.   One can use `wland_v001` like the original Wageningen model, but it offers many more functionalities (hydrological response units, elevated regions, bidirectional coupling with other models, etc.).   However, I have no good idea how to express that.  `wland_wag_plus` or `wland_wag_ext`???

`meteo_glob_larsim` adds some additional equations to Thompson's paper ("Necker-Korrektur").  For `evap`, we decided on `evap_aet_morsim`, which means something like "LARSIM version of MORECS".  So, it could make sense to reuse this naming convention for `meteo`: `meteo_glob_morsim` and `meteo_sd_morsim`.  (If not, we should eventually rename `evap_aet_morsim`.)

**Comment by BGWKlein** [comment]
I would interpret the name wland_wag as the HydPy model using wageningen equations for the walrus part

**Comment by BGWKlein** [comment]
lstream:
I would extract `lstream` from the HydPy-L model family as a new model family
probable names:

`kinw_will`(iams) or `kinw_williams` for `lstream_v001`
`kinw_will(iams)_ext` or `kinw_williams_ext` for `lstream_v002`

`kinw` stands for kinematic wave
`ext` for external rating curve

**Comment by tyralla** [comment]
I updated all `evap` and `meteo` model names and descriptions.

**Comment by tyralla** [comment]
For now, I selected `meteo_glob_morsim` and `meteo_sd_morsim`, which are still not finally decided. Everything else should have been already settled.

**Comment by tyralla** [comment]
> I would interpret the name wland_wag as the HydPy model using wageningen equations for the walrus part

Okay, I adjusted the name and both descriptions:
- `wland_wag`: HydPy-W-Wag (extended version of the original Wageningen WALRUS model)
- `wland_gd`: HydPy-W-GD (extended version of the WALRUS model with modified groundwater dynamics)

**Comment by tyralla** [comment]
> lstream: I would extract `lstream` from the HydPy-L model family as a new model family ...

Definitely a good idea.  There are currently three base models and four application models left that belong to a "land" model family:

- `lstream_v001` and `lstream_v002` (HydPy-L)
- `llake_v1` (HydPy-L)
- `hbranch_v1` (HydPy-H)
 
We have already decided to remove `llake_v1`.   If we move `lstream_v001` and `lstream_v002` to another model family, only `hbranch_v1` is left in a "land" model family.   (It seems I forgot to mention it in the table.) We could also move it to a new model family for consistency.

**Comment by BGWKlein** [comment]
I would extract hbranch from land model, probably shift to a model family "branch" for all branch models?
Gruß Bastian

-----Ursprüngliche Nachricht-----
Von: Christoph Tyralla ***@***.***> 
Gesendet: Montag, 22. April 2024 10:52
An: hydpy-dev/hydpy ***@***.***>
Cc: Klein, Bastian, M2, B40 ***@***.***>; Comment ***@***.***>
Betreff: Re: [hydpy-dev/hydpy] Model names in HydPy 6.0 (Issue #99)

	lstream: I would extract lstream from the HydPy-L model family as a new model family ...

Definitely a good idea. There are currently three base models and four application models left that belong to a "land" model family:

*	lstream_v001 and lstream_v002 (HydPy-L)
*	llake_v1 (HydPy-L)
*	hbranch_v1 (HydPy-H)

We have already decided to remove llake_v1. If we move lstream_v001 and lstream_v002 to another model family, only hbranch_v1 is left in a "land" model family. (It seems I forgot to mention it in the table.) We could also move it to a new model family for consistency.

**Comment by tyralla** [comment]
> I would extract hbranch from land model, probably shift to a model family "branch" for all branch models?

A suggestion to not increase the number of model families too much: Maybe we could move `hbranch_v1` to the[ HydPy-Exch(ange)](https://hydpy-dev.github.io/hydpy/5.0/HydPy-Exch.html) family.  The final model names of this family then could be:
- `exch_weir_hbv96` (instead of `exch_v001` or `exch_hweir`)
- `exch_branch_hbv96` (instead of `hbranch_v001`)
- `exch_waterlevel` (new)

**Comment by tyralla** [comment]
Or we could move `hbranch_v1` to [HydPy-Conv](https://hydpy-dev.github.io/hydpy/5.0/HydPy-C.html).

**Comment by BGWKlein** [comment]
From my point of view it seems a good idea to shift hbranch to the exch family

-----Ursprüngliche Nachricht-----
Von: Christoph Tyralla ***@***.***> 
Gesendet: Montag, 22. April 2024 13:09
An: hydpy-dev/hydpy ***@***.***>
Cc: Klein, Bastian, M2, B40 ***@***.***>; Comment ***@***.***>
Betreff: Re: [hydpy-dev/hydpy] Model names in HydPy 6.0 (Issue #99)

	I would extract hbranch from land model, probably shift to a model family "branch" for all branch models?

A suggestion to not increase the number of model families too much: Maybe we could move hbranch_v1 to the HydPy-Exch(ange) <https://hydpy-dev.github.io/hydpy/5.0/HydPy-Exch.html>  family. The final model names of this family then could be:

*	exch_weir_hbv96 (instead of exch_v001 or exch_hweir)
*	exch_branch_hbv96 (instead of hbranch_v001)
*	exch_waterlevel (new)

**Comment by tyralla** [comment]
I agree.  Technically, moving `hbranch` to HydPy-Conv would make sense, but hydrologically "branches" and "weirs" are quite close to each other (closer than "branches" and "interpolation algorithms"). 

I will adjust the `exch` names as suggested.

**Comment by tyralla** [comment]
Following the last changes, should we rename `dam_llake`, `dam_lretention`, and `dam_lreservoir` to  `dam_lake_larsim`, `dam_retention_larsim`, and `dam_reservoir_larsim`?

**Comment by tyralla** [comment]
I added (preliminary) names and descriptions for the new `gland` and `rconc` models.

We finally decided on `gland` but are still looking for a more general name than `rconc`.

The descriptions are only drafts.  I mentioned airGR (but not INREA) and wrote "ODE-based" to clarify that `rconc_nash` works with explicit storages instead of a UH-like convolution (neither sure this is necessary or understandable).

**Comment by tyralla** [comment]
I added `rconc_uh` and `rconc_nash` to the list.

**Comment by tyralla** [comment]
I renamed `q_walrus` to `wq_walrus`.

**Comment by sivogel** [comment]
I updated names for gland and snow

**Comment by tyralla** [comment]
I added `wq_trapeze` and `wq_trapeze_strickler` to the list.

**Comment by tyralla** [comment]
I added `sw1d_pump` to the list.

**Comment by tyralla** [comment]
I added  `ga_garto_submodel1` and adjusted the documentation-style name of `ga_garto`.   No nice solution - just in case we will not be able to work on #141 soon enough

**Comment by tyralla** [comment]
I will use names like "HydPy-Dam-V1 (dam model, version 1)" for `dam_v001` to `dam_v005`.  This is also a temporary solution.  We considered merging these five models into one by extracting all "special features" into new submodels.  Still, it is currently unclear if this is feasible and, if so, if we can work on it before releasing HydPy 6.0.  (@sivogel: we do not have a separate issue or any progress on this matter, do we?)

**Comment by tyralla** [comment]
I changed `lstream_v001` to `kinw_williams` and `lstream_v002` to `kinw_williams_ext` in the list and added documentation-style names.

**Comment by tyralla** [comment]
I implemented everything as discussed.  

I will open a separate issue regarding the further development of `dam_v001` to `dam_v005`.  

I kept the original variable names for `exch_branch_hbv96`, `kinw_williams`, and `kinw_williams_ext`.   His might be okay for  `exch_branch_hbv96` (please open another issue if you think differently) but suboptimal for `kinw_williams` and `kinw_williams_ext`, which still rely on German abbreviations stemming from LARSIM.  I left a warning in its documentation to clarify that one must expect breaking changes due to this and other issues with `kinw_williams` and `kinw_williams_ext.

We don't have separation into model groups and subgroups anymore!  Now, every model family consists of exactly one base model, and all its application models are derived from it.  So, we could rename "Model Collection" (a term I never liked too much) to "Model Families" to further increase the consistency of terms used in the documentation.
